from Helpers import DMHelper

async def ListCommands(message):
  # Generate message that lists all commands, split into 2 messages due to character limit
  CommandsMessage = "**All times provided to the but must be in UTC time for the bot to function properly:**\n**Basic commands:**\n**!addrun**, used to start a conversation with the bot that will guide you through the process to create a run\n**!adddefaulttemplates**, used to add some default templates for FFXIV example use: !adddefaulttemplates\n**!commands**, lists all supported commands example use: !commands\n**!dismiss**, used to remove a member from the run example use: !dismiss 2 (this is the number you see after Run:) @UserName (you can just tag the user you want to dismiss, only the organizer of the run is allowed to dismiss members)\n**!myruns**, show upcoming runs you've signed up for up to a maximum of 5 example use: !myruns\n**!roles**, lists all available roles example use: !roles\n**!runs**, used to retrieve all runs planned on a specific date example use: !runs 01-08-2021\n**!templates**, lists all available templates that can be used to create a run with example use: !templates\n**Advanced commands:**\n**!create**, used to create a run example use without template (for if you don't want to go through a conversation with the bot):\n!create TestRaid !date 01-08-2021 19:00 !nrofplayers 24 !nroftanks 3 !nrofdps 15 !nrofhealers 6 !role tank\nExample use with template:\n!create TestRaid !date 01-08-2021 19:00 !template raid !role tank\n**!addtemplate**, used to create a custom template example use: !addtemplate TestTemplate !nrofplayers 8 !nroftanks 2 !nrofdps 4 !nrofhealers 2\n**!updatetemplate**, used to update an existing template example use: !updatetemplate TestTemplate !nrofplayers 8 !nroftanks 2 !nrofdps 4 !nrofhealers 2 (only the creator of the template is allowed to update)\n**!deletetemplate**, used to delete a template example use: !deletetemplate TestTemplate (only the creator of the template is allowed to delete)"
  
  ButtonExplanationsMessage = "**Button explanations:**\n**Role (Tank/DPS/Healer) buttons**, if you're not part of a run clicking one of the role buttons will add you to that run on that role\nIf you're already part of the run and you click on the same role button as the role you've signed up with you'll be given the option to withdraw from the run\nIf you're already part of the run and you click on another role button then the role you've signed up with you'll be given the option to change your role for the run\n**Rally button**, you can use this button to tag all members that are signed up to this specific run (this will only work from 1 hour before the start time of the run up until the start time and can only be executed by players who are also signed up to this run up to a maximum amount of 3 times)\n**Reschedule button**, gives the organizer of the run the option to reschedule the run to another date (upon rescheduling all members besides the organizer will be removed from the run)\n**Cancel button**, gives the organizer of the run the option to cancel the run"

  await DMHelper.DMUser(message, CommandsMessage)
  await DMHelper.DMUser(message, ButtonExplanationsMessage)
  return